title: The UK-China Symposium on Translation Studies
description: > # this means to ignore newlines until "baseurl:"
  Translation and interpreting studies in the East and West: Advances, Convergence and Divergence
baseurl: "" # the subpath of your site, e.g. /blog
url: "ukchsymts.github.io/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"


google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)


# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-time-machine
